builds:
- id:
  dir: .
  main: .
  env:
    - CGO_ENABLED=0
  flags:
  - -tags
  - netgo
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X gitlab.com/BobyMCbobs/go-http-server/pkg/common.AppBuildVersion={{ .Env.APP_BUILD_VERSION }}
  - -X gitlab.com/BobyMCbobs/go-http-server/pkg/common.AppBuildHash={{ .Env.APP_BUILD_HASH }}
  - -X gitlab.com/BobyMCbobs/go-http-server/pkg/common.AppBuildDate={{ .Env.APP_BUILD_DATE }}
  - -X gitlab.com/BobyMCbobs/go-http-server/pkg/common.AppBuildMode={{ .Env.APP_BUILD_MODE }}

defaultPlatforms:
- linux/arm64
- linux/arm/v6
- linux/riscv64
- linux/amd64
- linux/386
