site_name: Go-HTTP-Server
strict: true
repo_name: "BobyMCbobs/go-http-server"
repo_url: https://gitlab.com/BobyMCbobs/go-http-server
site_url: https://BobyMCbobs.gitlab.io/go-http-server

markdown_extensions:
  - codehilite
  - meta
  - toc:
      permalink: " ¶"

plugins:
  - material-plausible

extra:
  analytics:
    provider: plausible
    domain: bobymcbobs.gitlab.io

theme:
  name: material
  features:
    - tabs
    - instant
  palette:
    primary: "blue"
    accent: "green"

nav:
  - Welcome: index.md
  - Configuration: configuration.md
  - Deployment: deployment.md
  - Development: development.md
  - Usage: usage.md
  - Contributing: contributing.md
