{{- if .Values.templateMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-http-server.fullname" . }}-templatemap
  labels:
    app: io.bobymcbobs.go-http-server
    {{- include "go-http-server.labels" . | nindent 4 }}
{{- if .Values.labels }}
{{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
data:
  "template.yaml": |
    {{- toYaml .Values.templateMap | nindent 4 }}
{{- end }}
