templateMap:
  title: Welcome to go-http-server
  body: "${BODY}"

extraEnv:
  - name: BODY
    value: |
      go-http-server is a fast, efficent scalable, minimal and secure web server from Safe Surfer.
      It supports SPA navigation (for Vue.js), as well as go html templating the index.html file upon serving.

      Find out more at:
        https://BobyMCbobs.gitlab.io/go-http-server

vuejsHistoryMode: true

initContainers:
  - name: prepare
    image: alpine:3.12
    volumeMounts:
      - name: app-site
        mountPath: /app/site
    command:
      - sh
      - -c
      - echo "<html><body><h1>{{ .title }}</h1><p>{{ .body }}</p></body></html>" > /app/site/index.html

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  realIPHeader: X-Real-Ip
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls:
    - hosts:
        - chart-example.local
      secretName: letsencrypt-prod

extraVolumes:
  - name: app-site
    emptyDir: {}

extraVolumeMounts:
  - name: app-site
    mountPath: /app/site
